server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    refresh:
      enable: true
    healthcheck:
      enabled: true


